- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: manisha.fun
  #   instances:
  #   - DB
  #   - BackenD
  #   - FrontenD
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: sg-0210a7b27894140c9 #replace with you AWS values
      image_id: ami-090252cbe067a9e58
    loop: 
    -DB
    -BackenD
    -FrontenD
    register: ec2_instances_info
  - name: print the o/p
    ansible.builtin.debug:
      msg: "The info: {{ec2_instances_info}}"